skip_tags: true
os:
  - Visual Studio 2015

platform:
  - Win32
  - x64

cache:
  - 'target -> appveyor.yml'
  - '%USERPROFILE%\.cargo'

branches:
  only:
    - master
    - /^release\/.+$/

environment:
  fast_finish: true
  DIST_DIR: '.'
  CARGO_HTTP_CHECK_REVOKE: false
  ZEUS_HOOK_BASE:
    secure: dcqtt6sxxBV0tDkXmPZOy6GJWwOsnexYCBqoT9RB/MyqwhhOhUgL9bOJgcYxpmzuWj6Oegku7usLQe2xceislPGSIXfrUz3iTD00ufTZqcI0T/8fNDagxNjVNpr5zj+DA/JjLgkqUyQ2+hIIAGtbpHnL0C+pjfuM2iHNNDOepyY=

  matrix:
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: stable
      target: x86_64-pc-windows-msvc

install:
  # Push job information to Zeus
  - npm install -g @zeus-ci/cli
  - zeus job update --status=pending -B "%APPVEYOR_PULL_REQUEST_TITLE%" -J "%APPVEYOR_JOB_NAME%" ||
      echo "%$APPVEYOR_REPO_BRANCH%" | findstr /V "release/">nul
  # Install rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - make test

on_success:
  - zeus job update --status=passed ||
      echo "%$APPVEYOR_REPO_BRANCH%" | findstr /V "release/">nul

on_failure:
  - zeus job update --status=failed ||
      echo "%$APPVEYOR_REPO_BRANCH%" | findstr /V "release/">nul
