minVersion: "0.10.0"
github:
  owner: getsentry
  repo: sentry-rust
changelogPolicy: auto

targets:
  - name: crates
  - name: gh-pages
  - name: github
  - name: registry
    type: sdk
    config:
      canonical: "cargo:sentry"
