minVersion: "0.15.0"
github:
  owner: getsentry
  repo: sentry-rust
changelogPolicy: auto

statusProvider:
  name: github
artifactProvider:
  name: none

targets:
  - name: crates
    noDevDeps: true
  - name: github
  - name: registry
    type: sdk
    config:
      canonical: "cargo:sentry"
