---
# Configuration for sentry-craft (https://github.com/getsentry/craft)
github:
  owner: getsentry
  repo: sentry-rust
targets:
  - name: crates
  - name: gh-pages
  - name: github
changelogPolicy: simple
