[package]
name = "sentry-types"
version = "0.49.1"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = """
Common reusable types for implementing the sentry.io protocol.
"""
readme = "README.md"
homepage = { workspace = true }
repository = { workspace = true }
license = "MIT"
keywords = ["protocol", "sentry"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
debugid = { workspace = true, features = ["serde"] }
hex = { workspace = true }
rand = { workspace = true }
sentry-time = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting", "parsing"] }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde"] }

[dev-dependencies]
rstest = { workspace = true }

[features]
default = ["protocol"]
protocol = []

[lints]
workspace = true
