[package]
name = "sentry-time"
version = "0.49.1"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = """
Time based functions supporting all targets including WASM.
"""
homepage.workspace = true
repository.workspace = true
license = "MIT"

[dependencies]
web-time = "1"
