[package]
name = "sentry-tracing"
version = "0.49.1"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = """
Sentry integration for the tracing and tracing-subscriber crates.
"""
readme = "README.md"
homepage = { workspace = true }
repository = { workspace = true }
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[dependencies]
bitflags = { workspace = true }
sentry-backtrace = { workspace = true, optional = true }
sentry-core = { workspace = true, features = ["client"] }
sentry-time.workspace = true
tracing-core = { workspace = true }
tracing-subscriber = { workspace = true, features = ["std"] }

[dev-dependencies]
log = { workspace = true }
sentry = { workspace = true, features = ["test", "tracing"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "registry"] }

[features]
default = []
backtrace = ["dep:sentry-backtrace"]
logs = ["sentry-core/logs"]

[lints]
workspace = true
