(function() {var implementors = {};
implementors["sentry"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"sentry/struct.ClientOptions.html\" title=\"struct sentry::ClientOptions\">ClientOptions</a>&gt;&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;T&gt; for <a class=\"struct\" href=\"sentry/struct.Client.html\" title=\"struct sentry::Client\">Client</a>",synthetic:false,types:["sentry::client::Client"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"sentry/internals/trait.IntoDsn.html\" title=\"trait sentry::internals::IntoDsn\">IntoDsn</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.tuple.html\">(</a>T, <a class=\"struct\" href=\"sentry/struct.ClientOptions.html\" title=\"struct sentry::ClientOptions\">ClientOptions</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.tuple.html\">)</a>&gt; for <a class=\"struct\" href=\"sentry/struct.ClientOptions.html\" title=\"struct sentry::ClientOptions\">ClientOptions</a>",synthetic:false,types:["sentry::client::ClientOptions"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"sentry/internals/trait.IntoDsn.html\" title=\"trait sentry::internals::IntoDsn\">IntoDsn</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;T&gt; for <a class=\"struct\" href=\"sentry/struct.ClientOptions.html\" title=\"struct sentry::ClientOptions\">ClientOptions</a>",synthetic:false,types:["sentry::client::ClientOptions"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
