[package]
name = "sentry-opentelemetry"
version = "0.49.1"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = """
Sentry integration for OpenTelemetry.
"""
readme = "README.md"
homepage = { workspace = true }
repository = { workspace = true }
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[dependencies]
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["trace"] }
sentry-core = { workspace = true, features = ["client"] }
sentry-time.workspace = true

[dev-dependencies]
opentelemetry_sdk = { workspace = true, features = ["testing", "trace"] }
sentry = { workspace = true, features = ["opentelemetry", "test"] }
sentry-core = { workspace = true, features = ["test"] }

[lints]
workspace = true
