[package]
name = "sentry-tower"
version = "0.49.1"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = """
Sentry integration for tower-based crates.
"""
readme = "README.md"
homepage = { workspace = true }
repository = { workspace = true }
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[dependencies]
axum = { workspace = true, optional = true }
http = { workspace = true, optional = true }
pin-project = { workspace = true, optional = true }
sentry-core = { workspace = true, features = ["client"] }
tower-layer = { workspace = true }
tower-service = { workspace = true }
url = { workspace = true, optional = true }

[dev-dependencies]
anyhow = { workspace = true }
prost = { workspace = true }
sentry = { workspace = true, features = ["test"] }
sentry-anyhow = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tonic = { workspace = true, features = ["transport"] }
tower = { workspace = true, features = ["timeout", "util"] }

[features]
default = []
axum-matched-path = ["axum/matched-path", "http"]
http = ["dep:http", "pin-project", "url"]

[lints]
workspace = true
