(function() {var implementors = {};
implementors["sentry"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"sentry/struct.Client.html\" title=\"struct sentry::Client\">Client</a>",synthetic:false,types:["sentry::client::Client"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"sentry/struct.ClientOptions.html\" title=\"struct sentry::ClientOptions\">ClientOptions</a>",synthetic:false,types:["sentry::client::ClientOptions"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"sentry/struct.Hub.html\" title=\"struct sentry::Hub\">Hub</a>",synthetic:false,types:["sentry::hub::Hub"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"sentry/struct.Scope.html\" title=\"struct sentry::Scope\">Scope</a>",synthetic:false,types:["sentry::scope::real::Scope"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"sentry/internals/struct.ScopeGuard.html\" title=\"struct sentry::internals::ScopeGuard\">ScopeGuard</a>",synthetic:false,types:["sentry::scope::real::ScopeGuard"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"sentry/internals/struct.HttpTransport.html\" title=\"struct sentry::internals::HttpTransport\">HttpTransport</a>",synthetic:false,types:["sentry::transport::HttpTransport"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
