name: Build documentation

on:
  workflow_call:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  doc:
    name: Build documentation
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings

    steps:
      - name: Checkout sources
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - run: rustup component add rust-docs

      - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2

      - name: Run cargo doc
        run: cargo doc --workspace --all-features --document-private-items --no-deps --locked
